apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
  - image: charlottecc/sandbox:version1.0
    name: node-web-app
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always